export const mockPositions = [
  {
    open_position: {
      id: 1,
      candidate_id: 22,
      project_id: 1,
      is_open: false,
      position_name: "Desarrollador Frontend",
    },
    project: {
      customer_id: 13,
      name: "Proyecto prueba",
      is_team_complete: true,
      id: 1,
      description: "Descripción Proyecto prueba",
    },
    soft_skill_ids: [1, 2],
    technology_ids: [1, 1],
  },
  {
    open_position: {
      id: 2,
      candidate_id: 51,
      project_id: 1,
      is_open: false,
      position_name: "Desarrollador Backend",
    },
    project: {
      customer_id: 13,
      name: "Proyecto prueba",
      is_team_complete: true,
      id: 1,
      description: "Descripción Proyecto prueba",
    },
    soft_skill_ids: [4, 4],
    technology_ids: [2, 6],
  },
  {
    open_position: {
      id: 3,
      candidate_id: 51,
      project_id: 2,
      is_open: false,
      position_name: "Desarrollador Frontend",
    },
    project: {
      customer_id: 59,
      name: "Proyecto prueba",
      is_team_complete: false,
      id: 2,
      description: "Descripción Proyecto prueba",
    },
    soft_skill_ids: [1, 2],
    technology_ids: [1, 1],
  },
  {
    open_position: {
      id: 4,
      candidate_id: null,
      project_id: 2,
      is_open: true,
      position_name: "Desarrollador Backend",
    },
    project: {
      customer_id: 59,
      name: "Proyecto prueba",
      is_team_complete: false,
      id: 2,
      description: "Descripción Proyecto prueba",
    },
    soft_skill_ids: [4, 4],
    technology_ids: [2, 6],
  },
  {
    open_position: {
      id: 5,
      candidate_id: null,
      project_id: 3,
      is_open: true,
      position_name: "FrontEnd Engineer",
    },
    project: {
      customer_id: 13,
      name: "My little first Proyect",
      is_team_complete: false,
      id: 3,
      description:
        "Este es un pequeño proyecto que busca cambiar la vida de todos.",
    },
    soft_skill_ids: [6, 6, 6, 4, 4, 4, 7, 7, 7],
    technology_ids: [3, 5, 23, 3, 5, 23, 3, 5, 23],
  },
  {
    open_position: {
      id: 6,
      candidate_id: null,
      project_id: 11,
      is_open: true,
      position_name: "Desarrollador Frontend",
    },
    project: {
      customer_id: 13,
      name: "Mi proyectoy",
      is_team_complete: false,
      id: 11,
      description: "Descripción proyecto pruebax",
    },
    soft_skill_ids: [1, 2],
    technology_ids: [1, 1],
  },
  {
    open_position: {
      id: 7,
      candidate_id: null,
      project_id: 11,
      is_open: true,
      position_name: "Desarrollador Backend",
    },
    project: {
      customer_id: 13,
      name: "Mi proyectoy",
      is_team_complete: false,
      id: 11,
      description: "Descripción proyecto pruebax",
    },
    soft_skill_ids: [4, 4],
    technology_ids: [2, 6],
  },
  {
    open_position: {
      id: 8,
      candidate_id: null,
      project_id: 12,
      is_open: true,
      position_name: "DevOps",
    },
    project: {
      customer_id: 13,
      name: "Proyecto Final II",
      is_team_complete: false,
      id: 12,
      description: "ÚLTIMO PROYECTO",
    },
    soft_skill_ids: [4, 1],
    technology_ids: [11, 11],
  },
  {
    open_position: {
      id: 9,
      candidate_id: null,
      project_id: 14,
      is_open: true,
      position_name: "Backend Engineer",
    },
    project: {
      customer_id: 59,
      name: "Camilo Project",
      is_team_complete: false,
      id: 14,
      description: "Este es un proyecto de prueba para probar la funcionalidad",
    },
    soft_skill_ids: [4, 4, 1, 1],
    technology_ids: [2, 7, 2, 7],
  },
  {
    open_position: {
      id: 10,
      candidate_id: null,
      project_id: 14,
      is_open: true,
      position_name: "Backend Engineer",
    },
    project: {
      customer_id: 59,
      name: "Camilo Project",
      is_team_complete: false,
      id: 14,
      description: "Este es un proyecto de prueba para probar la funcionalidad",
    },
    soft_skill_ids: [4, 4, 1, 1],
    technology_ids: [2, 7, 2, 7],
  },
  {
    open_position: {
      id: 11,
      candidate_id: null,
      project_id: 15,
      is_open: true,
      position_name: "FULLSTACK",
    },
    project: {
      customer_id: 13,
      name: "Proyecto Final IV",
      is_team_complete: false,
      id: 15,
      description: "TEST EQUIPOS",
    },
    soft_skill_ids: [2, 2, 2, 2],
    technology_ids: [8, 11, 14, 23],
  },
  {
    open_position: {
      id: 12,
      candidate_id: null,
      project_id: 15,
      is_open: true,
      position_name: "FULLSTACK",
    },
    project: {
      customer_id: 13,
      name: "Proyecto Final IV",
      is_team_complete: false,
      id: 15,
      description: "TEST EQUIPOS",
    },
    soft_skill_ids: [2, 2, 2, 2],
    technology_ids: [8, 11, 14, 23],
  },
  {
    open_position: {
      id: 13,
      candidate_id: null,
      project_id: 15,
      is_open: true,
      position_name: "FULLSTACK",
    },
    project: {
      customer_id: 13,
      name: "Proyecto Final IV",
      is_team_complete: false,
      id: 15,
      description: "TEST EQUIPOS",
    },
    soft_skill_ids: [2, 2, 2, 2],
    technology_ids: [8, 11, 14, 23],
  },
  {
    open_position: {
      id: 14,
      candidate_id: null,
      project_id: 15,
      is_open: true,
      position_name: "DEVOPS",
    },
    project: {
      customer_id: 13,
      name: "Proyecto Final IV",
      is_team_complete: false,
      id: 15,
      description: "TEST EQUIPOS",
    },
    soft_skill_ids: [6, 6, 6],
    technology_ids: [8, 9, 14],
  },
  {
    open_position: {
      id: 15,
      candidate_id: null,
      project_id: 15,
      is_open: true,
      position_name: "DEVOPS",
    },
    project: {
      customer_id: 13,
      name: "Proyecto Final IV",
      is_team_complete: false,
      id: 15,
      description: "TEST EQUIPOS",
    },
    soft_skill_ids: [6, 6, 6],
    technology_ids: [8, 9, 14],
  },
  {
    open_position: {
      id: 16,
      candidate_id: 20,
      project_id: 16,
      is_open: true,
      position_name: "Data scientist",
    },
    project: {
      customer_id: 59,
      name: "Test Project 5N",
      is_team_complete: false,
      id: 16,
      description: "Test project",
    },
    soft_skill_ids: [7, 4],
    technology_ids: [18, 18],
  },
  {
    open_position: {
      id: 17,
      candidate_id: 69,
      project_id: 17,
      is_open: false,
      position_name: "FRONTEND",
    },
    project: {
      customer_id: 13,
      name: "Proyecto Final MISO",
      is_team_complete: true,
      id: 17,
      description:
        "ESTE PROYECTO ES SOBRE DEMOSTRAR LOS CONOCIMIENTOS ADQUIRIDOS DURANTE LA MAESTRIA EN LA UNIANDES",
    },
    soft_skill_ids: [6, 6, 6, 6, 1, 1, 1, 1],
    technology_ids: [1, 3, 5, 11, 1, 3, 5, 11],
  },
  {
    open_position: {
      id: 18,
      candidate_id: 20,
      project_id: 18,
      is_open: false,
      position_name: "frontend",
    },
    project: {
      customer_id: 13,
      name: "proyecto final sustentación",
      is_team_complete: true,
      id: 18,
      description: "adasdasdasdasdas",
    },
    soft_skill_ids: [6, 6, 1, 1, 4, 4],
    technology_ids: [8, 13, 8, 13, 8, 13],
  },
  {
    open_position: {
      id: 19,
      candidate_id: 20,
      project_id: 18,
      is_open: false,
      position_name: "frontend",
    },
    project: {
      customer_id: 13,
      name: "proyecto final sustentación",
      is_team_complete: true,
      id: 18,
      description: "adasdasdasdasdas",
    },
    soft_skill_ids: [6, 6, 1, 1, 4, 4],
    technology_ids: [8, 13, 8, 13, 8, 13],
  },
];
