import './globals.css'
import type { Metadata } from 'next'
import { Outfit, Philosopher } from 'next/font/google'

const outfit = Outfit({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
})

const philosopher = Philosopher({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-roboto-mono',
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'ABC Jobs',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html
      lang="en"
      className={`${outfit.variable} ${philosopher.variable} font-sans`}
    >
      <body>{children}</body>
    </html>
  )
}
