import "./globals.css";
import type { Metadata } from "next";
import ThemeRegistry from "./ThemeRegistry";
import IntegrationNotistack from "@/components/toast/toast-provider";
import ClientSessionProvider from "./context/client-provider";

export const metadata: Metadata = {
  title: "ABC Jobs",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ClientSessionProvider>
          <ThemeRegistry options={{ key: "mui" }}>
            <IntegrationNotistack>{children}</IntegrationNotistack>
          </ThemeRegistry>
        </ClientSessionProvider>
      </body>
    </html>
  );
}
