import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { NextIntlClientProvider } from "next-intl";

import "./globals.css";
import ThemeRegistry from "./ThemeRegistry";
import IntegrationNotistack from "@/components/toast/toast-provider";
import ClientSessionProvider from "./context/client-provider";

export const metadata: Metadata = {
  title: "ABC Jobs",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return [{ locale: "en" }, { locale: "es" }];
}

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  let messages;
  try {
    messages = (await import(`../../lang/${params.locale}.json`)).default;
  } catch (error) {
    notFound();
  }
  return (
    <html lang="en">
      <body>
        <NextIntlClientProvider locale={params.locale} messages={messages}>
          <ClientSessionProvider>
            <ThemeRegistry options={{ key: "mui" }}>
              <IntegrationNotistack>{children}</IntegrationNotistack>
            </ThemeRegistry>
          </ClientSessionProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
