export const tech_skills = [
  { value: "1", label: "Frontend" },
  { value: "2", label: "Backend" },
  { value: "3", label: "ReactJS" },
  { value: "4", label: "NodeJS" },
  { value: "5", label: "NextJS" },
  { value: "6", label: "Python" },
  { value: "7", label: "Flask" },
  { value: "8", label: "AWS" },
  { value: "9", label: "Architecture" },
  { value: "10", label: "NestJS" },
  { value: "11", label: "Angular" },
  { value: "12", label: "GCP" },
  { value: "13", label: "Azure" },
  { value: "14", label: "DevOps" },
  { value: "15", label: "Java" },
  { value: "16", label: "SpringBoot" },
  { value: "17", label: "FastAPI" },
  { value: "18", label: "Data Science" },
  { value: "19", label: "SQL" },
  { value: "20", label: "NoSQL" },
  { value: "21", label: "MongoDB" },
  { value: "22", label: "Redis" },
  { value: "23", label: "CSS" },
  { value: "24", label: "Typescript" },
];

export const soft_skills = [
  { value: "1", label: "Leadership" },
  { value: "2", label: "Responsibility" },
  { value: "3", label: "Ownership" },
  { value: "4", label: "Communication" },
  { value: "5", label: "Teamwork" },
  { value: "6", label: "Adaptability" },
  { value: "7", label: "Empathy" },
  { value: "8", label: "Management" },
];
